steps:
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - >
      gcloud deploy apply --file clouddeploy.yaml --region=asia-south1 --project=accops-poc-gdc-e;
      gcloud deploy releases create gdce-release-$SHORT_SHA \
                          --delivery-pipeline gdce-pipeline \
                          --description "$(git log -1  --pretty='%s')" \
                          --region=asia-south1
options:
  logging: CLOUD_LOGGING_ONLY
